### ISSUE TITLE
Track availability

### ISSUE THREAD

**Issue by MattiSG** [ambanum/OpenTermsArchive.org#100]
- Create a probe with https://uptimerobot.com
- Notify admin@ota if there is a problem

**Comment by clementbiron** [comment]
- [x]  I have created a uptimerobot account and updated our safety box with account access. 
- [x] I have configured uptimerobot to ping opentermsarchive.org every 5 minutes and notify admin@opentermsarchives.org if there is a problem.

![image](https://user-images.githubusercontent.com/364319/151368130-c18e30ff-3ebe-4912-a621-269d2649f18f.png)
