### ISSUE TITLE
Wrong list of services

### ISSUE THREAD

**Issue by clementbiron** [ambanum/OpenTermsArchive.org#102]
The list of services available for subscription by email is wrong: some services are missing.

I think it's because we generate this list from the dataset.

![image](https://user-images.githubusercontent.com/364319/153832712-e9763a3f-9551-4b2b-a94b-c358b4af75f9.png)

**Comment by btrd** [comment]
It seems worst now :/
https://opentermsarchive.org/fr/subscribe

![Capture d’écran 2022-03-30 à 16 36 06](https://user-images.githubusercontent.com/1385737/160862311-a6dcc7dd-e5e1-4a49-b923-33cd58cc26e0.png)
