### ISSUE TITLE
Ensure title of homepage is Open Terms Archive in every language

### ISSUE THREAD

**Issue by MattiSG** [ambanum/OpenTermsArchive.org#120]
Currently, Open Terms Archive is not very SEO'd because the homepage is indexed on all of `/`, `/en` and `/fr`. The `title` of `/en` and `/fr` seems to be the value of the `<h1>` instead of `Open Terms Archive`.

<img width="552" alt="Screen Shot 2022-05-03 at 16 58 00" src="https://user-images.githubusercontent.com/222463/166467177-f30f23be-4a3b-4ceb-a3f4-fdef2e32f2a7.png">

**Comment by clementbiron** [comment]
`<Head>` contain in french :
```html
<title>Open Terms Archive</title>
<meta name="description" content="Suivre les engagements contractuels des principaux fournisseurs de services en ligne"/>
```
and in english:
```html
<title>Open Terms Archive</title>
<meta name="description" content="We track every change to terms of services to shift the power balance against big tech."/>
```

I thought Google would use the `<meta name="description" content="" />` to generate the SERP title but according to [Google Search documentation](https://developers.google.com/search/blog/2021/08/update-to-generating-page-titles#how-titles-are-generated), Google prefer using `<h1>`content fot that, but it seems to depend on the content of the `<title>` tag.

So:
1. We can try to update the `<title>` value from "Open Terms Archive" to "We track every change to terms of services to shift the power balance against big tech." (the meta desc value) and wait a few weeks to see if the changes are taken into account.
2. Depending on the result, change the content of the `<h1>`  of the homepage.

@MattiSG what do you think ?

**Comment by martinratinaud** [comment]
This is really weird that all these pages are indexed like that as the <link rel="alternate"> are setup correctly.

Can we add this to search console to understand what is wrong?

**Comment by martinratinaud** [comment]
You're definitely right, sitemap is wrong.
@clementbiron check this https://developers.google.com/search/docs/advanced/crawling/localized-versions
