### ISSUE TITLE
Apply security policies

### ISSUE THREAD

**Issue by MattiSG** [ambanum/OpenTermsArchive.org#137]
- [x] Content Security Policy (CSP) header
- [x] X-Content-Type-Options header
- [x] X-Frame-Options (XFO) header
- [x] X-XSS-Protection header

**Comment by martinratinaud** [comment]
Here is an interesting way of applying some of these security fixes

https://oslavdev.medium.com/protect-your-next-js-app-with-security-headers-7f70f4a95d63
