### ISSUE TITLE
Contribution interface : hCaptcha

### ISSUE THREAD

**Issue by clementbiron** [ambanum/OpenTermsArchive.org#15]
Trying to add `https://pubhelp.taboola.com/hc/en-us/articles/360033751274-Taboola-Publisher-Policy#` 

return a hCaptcha clickable but nothing happen

**Comment by martinratinaud** [comment]
Working now with this url

https://www.opentermsarchive.org/en/contribute/service?step=2&url=https%3A%2F%2Fpubhelp.taboola.com%2Fhc%2Fen-us%2Farticles%2F360033751274-Taboola-Publisher-Policy%23
