### ISSUE TITLE
Improve static pages editability

### ISSUE THREAD

**Issue by clementbiron** [ambanum/OpenTermsArchive.org#187]
I think the management of static pages would be clearer if 
- each static page would be located at `/content/pages/${locale}/${pagename}.mdx` 
- you can define which layout you use in the frontmatter with `layout: ${layoutName}` (sorry @martinratinaud for telling you the opposite by phone yesterday).

**Comment by martinratinaud** [comment]
Sure, do you already have several layouts in mind?

My guess is that it would be easier to define sections that can be included in the mdx than whole layouts but we can discuss this with real world use cases

**Comment by clementbiron** [comment]
Implemented with #191 and using different layout is possible without defining a frontmatter value as it is done in #185
