### ISSUE TITLE
Make "Gatekeepers" services first in the select box for subscribing to services change

### ISSUE THREAD

**Issue by martinratinaud** [ambanum/OpenTermsArchive.org#21]
As we do not want to introduce too much bias on which service changes should be followed or not, we decided to use a metric to decide whether or not a service might be more interesting for users.

This metric is the notion of being a Gatekeeper https://ec.europa.eu/info/strategy/priorities-2019-2024/europe-fit-digital-age/digital-markets-act-ensuring-fair-and-open-digital-markets_en

@trujilloelsa can you please list them here so that we can put them at the top of the select box

Thanks very much

**Comment by trujilloelsa** [comment]
https://ec.europa.eu/commission/presscorner/detail/en/qanda_20_2349
Specifically, there are three main cumulative criteria that bring a company under the scope of the Digital Markets Act.
One of them is the control of an important gateway for business users towards final consumers. This is presumed to be the case if the company operates a core platform service with more than 45 million monthly active end users established or located in the EU and more than 10 000 yearly active business users established in the EU in the last financial year.
**These online services have > 45 monthly active end users established or located in the EU.**
Amazon.com
Apple
Facebook
Google
Gmail
Instagram
Spotify
TikTok
WhatsApp
YouTube

**Comment by martinratinaud** [comment]
deployed on https://www.opentermsarchive.org/
