### ISSUE TITLE
Remove dependency on yarn

### ISSUE THREAD

**Issue by MattiSG** [ambanum/OpenTermsArchive.org#52]
In order to maximise contribuability, the default package manager should be `npm` as it is bundled with Node and installed by default.

**Comment by MattiSG** [comment]
@martinratinaud your input on this topic would be very useful to understand the consequences and if the RoI is good enough 😊

**Comment by martinratinaud** [comment]
Not any.

Yarn is my go to tool because it's the one used by next and create-react-app and that's why I use it by default.

I think everything will work fine with `npm` and it will be more coherent with OpenTermsArchive core.

**Comment by martinratinaud** [comment]
@clementbiron You said you wanted to check something on this right?

On my end I think it's ok and we can close

**Comment by martinratinaud** [comment]
Done in latest `main`
