### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by MattiSG** [ambanum/OpenTermsArchive.org#59]
Apply a EUPL license:

- Add the file to the root of the repository.
- Add a recap at the bottom of the README (see https://github.com/ambanum/OpenTermsArchive).

**Comment by MattiSG** [comment]
@clementbiron it seems “Add a recap at the bottom of the README” was not done in #67 😉

**Comment by clementbiron** [comment]
This is a mistake, I didn't do it in #67 but here https://github.com/ambanum/OpenTermsArchive.org/commit/fff16b229cca7202c47dd4425f6d11a1f57c00a8
