### ISSUE TITLE
Re-architect homepage

### ISSUE THREAD

**Issue by MattiSG** [ambanum/OpenTermsArchive.org#62]
After user testing, and in order to improve the readability of the value proposition.

### Blocks (in reading order)

- Mission statement
- What it is
- How it works (4 steps)
- CTA pro: dataset, API beta
- CTA public: Twitter, Mail, GitHub
- Reuses
- Stats
- FOSS & Contributors
- Partners
- Press

### Information that is present in the current version and has not been rearchitected

- Values
- Contact
- How it works page
- Press page
- Case studies page
- Privacy policy
- ToS
- Dashboard page

**Comment by MattiSG** [comment]
_Notes from synchronous work session with @clementbiron and @MattiSG._

# Texts

## Mission statement

Shift the power balance against large digital platforms
Rééquilibrer le rapport de force face aux grandes plateformes numériques

## What it is

Open Terms Archive stores every change to the terms of use of digital services. This database enables users, NGOs and regulators to assess the loyalty of those companies.
Open Terms Archive enregistre chaque modification des conditions d'utilisation des services numériques. Cette base de données permet aux utilisateurs et régulateurs d'évaluer la loyauté de ces entreprises.

## How it works

1. Identification
Les documents contractuels d'un service numérique à suivre sont listés par des contributeurs bénévoles.
2. Archivage
Plusieurs fois par jour, nos robots téléchargent et archivent publiquement les documents listés.
3. Détection
Lorsque des modifications sont repérées, elles sont enregistrées et exposées.
4. Publication
L'ensemble de toutes les versions enregistrées est publié dans un jeu de données.

## CTA Pro

Télécharger pour analyser

## CTA Public

Quand les services que nous utilisons au quotidien changent leurs règles, nous sommes les premiers concernés.

- Lisez des modifications intéressantes sur Twitter → Suivre @OpenTerms
- Suivez les modifications d'un document donné → S'abonner par mail / ou par RSS
- Explorez l'historique de n'importe quel document → Naviguer sur GitHub / ou télécharger le jeu de données

# Other notes

- We'll switch the Reuses block to a cards layout.
- We'll move the Mail subscription form to its own page.

**Comment by MattiSG** [comment]
# Texts

## Reuses

La communauté d'Open Terms Archive construit des outils pour rééquilibrer le rapport de force face aux grandes plateformes numériques.

Scripta Manent : Consolide l'intégralité des modifications d'un document contractuel entre deux dates arbitraires.

Lisibilité des documents : Calcule la lisibilité et le niveau d'études nécessaires pour comprendre un document contractuel.

Votre outil : Si vous souhaitez développer un outil basé sur Open Terms Archive, contactez-nous !

## FOSS

Commun contributif
Open Terms Archive est un logiciel libre et ouvert. Toute entité peut le réutiliser et le modifier librement, sous seule condition de partager ses améliorations avec la communauté qui le construit.
Le produit est construit collaborativement par toutes les entités qui l'utilisent et y contribuent.
→ [En savoir plus](./about)

# How it works page

**Dropped**: its contents are too technical for the general public, and are a duplicate of the CONTRIBUTING file for a technical audience that is actually likely to contribute. The simple process overview is now on the homepage.

# Illustrations of process

Use screenshots to demonstrate the value and simplicity.

Choose a very famous service that embodies the goal, and keep the same service and document throughout.

1. Screenshot of service declaration. Use a simplified version that contains only `Terms of Service` and `Privacy Policy` and `fetch` and `select`.
2. Screenshot of process log, focused on the Facebook treatment.
3. Screenshot of a diff in “rich diff” view. Use the Privacy Policy [change](https://github.com/ambanum/OpenTermsArchive-versions/commit/80d0a20ba6f01994cf9637ca315113e13c717e4f?short_path=e43a595#diff-e43a59590f4f051a818725f7b8453d6db4b26ce8ad524d71bc8d8293d72bc28c) that occurred when jurisdiction switched from US to EU, and focus on the “Face recognition” paragraph: it is a major issue, makes the importance of such changes understandable to everyone, is easily readable, and serves a diplomatic purpose by demonstrating EU intrinsic superiority for data protection.
4. Screenshot of dataset expanded in column view, with the whole `Facebook/Privacy Policy/ 2021-10-07.md` path expanded, showing where the above example could be accessed.

# About page

### Open Terms Archive est un logiciel libre et ouvert visant à devenir un commun numérique

Son code source est fourni sous une licence <abbr title="European Union Public License">EUPL</abbr>. Cela signifie qu'il peut être librement réutilisé et modifié, tant que ces modifications soient mises à disposition sous les mêmes conditions. Cela signifie également que les décisions d'évolution du logiciel seront progressivement prises de manière démocratique au fur et à mesure que la communauté qui le construit s'agrandira.

**Nous recherchons des financements pour développer les usages et garantir la pérennité d'Open Terms Archive. Vous connaissez des moyens de nous aider ? Contactez-nous !**

### Équipe cœur

L'équipe qui fabrique et fait grandir Open Terms Archive est incubée au sein du Bureau de l'Ambassadeur pour les affaires numériques.

Équipe cœur : Matti, Nicolas, Clément, Martin, Elsa
Alumnis : Siegrid
Financeurs : MEAE, France Relance, UE

### Contributeurs

Toute amélioration du logiciel, peu importe sa forme, bénéficie à toute la communauté. Le produit Open Terms Archive ne serait pas le même sans ces contributions.

Avatars (attention, il faudra filtrer les robots et les membres de l'équipe cœur).
Logos : ToS;DR, PEReN, AmbNum, GDI

# Press

**Dropped**: the need to establish credibility is less strong now, and the dedicated Media page does a much better job.

# Stats

**Dropped**: we will integrate the dashboard properly in a dedicated sprint.

**Comment by MattiSG** [comment]
_Notes from synchronous work session with @clementbiron and @MattiSG._

As seen with @michielbdejong this morning, we are welcome to list @tosdr and TOSback as reusers of Open Terms Archive 😃

Hence the following reuses:

### Terms of Service; Didn’t Read

Permet aux utilisateurs de donner collaborativement une note aux conditions d’utilisation selon le respect de leurs droits.

By: ToS;DR.

### TOSback

L’ancêtre d’Open Terms Archive ! Depuis octobre 2020, les changements affichés sont fournis par une instance dédiée d’Open Terms Archive.

By: ToS;DR & Electronic Frontier Foundation

- - - -

@clementbiron please make sure that the logos reflect what is described in the previous message 🙂

**Comment by MattiSG** [comment]
After feedback from @Ndpnt, we'll adjust to the following text:

**Title** (“mission statement”): Quand les services que nous utilisons au quotidien changent leurs règles du jeu, nous sommes les premiers concernés.
**Subtitle** (“what it is”): Open Terms Archive enregistre chaque modification des conditions d'utilisation des services numériques. Une communauté de réutilisateurs évalue la loyauté des entreprises qui fournissent ces services grâce à la base de données de ces modifications. Nous rééquilibrons ainsi le rapport de force avec les grandes plateformes numériques.

I have tried several adjustments, but I don't manage to not have strong duplication between the Subtitle part and a potential Introduction to the How it works block.
I believe now the best way forward is to do user testing.

**Comment by clementbiron** [comment]
@MattiSG 

Too much text in my opinion, see below

![image](https://user-images.githubusercontent.com/364319/145885224-0112a3a8-88de-4603-b3d3-edbfd85a00f9.png)

I propose:

Title (“mission statement”): Quand les grandes plateformes numériques changent leurs règles, nous sommes les premiers concernés.
Subtitle (“what it is”): Open Terms Archive enregistre chaque modification des conditions d'utilisation pour évaluer la loyauté des entreprises qui offrent ces services et rééquilibrer le rapport de force.

![image](https://user-images.githubusercontent.com/364319/145886410-80bd5f09-40df-4c40-b4ad-7842b1911117.png)

**Comment by Ndpnt** [comment]
Maybe lower the title size?

**Comment by clementbiron** [comment]
I would prefer not to change the size since it is a style used in other pages.

**Comment by clementbiron** [comment]
Ok i reduce a little bit the `h1` size and it looks great.

![image](https://user-images.githubusercontent.com/364319/145967291-f9aef87c-f1c4-420c-b296-af5f073fb78a.png)

I still think that the subtitle has too much text, so the proposal below seems to me better.

![image](https://user-images.githubusercontent.com/364319/145967647-a7df5fb1-2c49-461e-949c-e4e1abf83041.png)

@Ndpnt @MattiSG what do you think ?

**Comment by MattiSG** [comment]
« Open Terms Archive enregistre chaque modification des conditions d'utilisation des services numériques. Une communauté de réutilisateurs analyse ces changements et rééquilibre ainsi le rapport de force avec les grandes plateformes. » ?

**Comment by clementbiron** [comment]
Look good to me, maybe we can shorten it a little bit ?

« Open Terms Archive enregistre chaque modification des conditions d'utilisation des services numériques. Une communauté  ~~de réutilisateurs~~ analyse ces changements et rééquilibre ainsi le rapport de force avec les grandes plateformes. »

**Comment by MattiSG** [comment]
Ok.
