### ISSUE TITLE
Switch to GitHub Flow

### ISSUE THREAD

**Issue by martinratinaud** [ambanum/OpenTermsArchive.org#81]
In order to have continuous deployment, we will switch to the following

- all modifications needs to pass through a PR against develop
- on merge on `develop`, site will be deployed on https://preprod.opentermsarchive.org in order to validate all changes
- one validated, a merge from `develop` in `main` will isuue a deployment on https://opentermsarchive.org

Also, branch protection needs to be setup

- [ ] no direct push on `main` nor `develop` (only through PR)
- [ ] PR in `develop` needs approval of at least one person
- [ ] PR in `main` do not need approval as it is supposed to have been verified on preprod first

**Comment by MattiSG** [comment]
I'm not sure I understand how this can have been closed 4 days ago yet #86 exists after it…? 🤔🙂 
Could we maybe have a synchronous call about it?

**Comment by MattiSG** [comment]
Okay, I just read the description of this issue. I did not understand the same thing. We are not currently operating under GitHub Flow. Let's discuss this asap :)
